functions = {"$aircraft": "The callsign of the selected aircraft.",
             "$alt": "The temporary, the sector entry/exit or the final altitude\n(if none of the previous are specified) of the selected aircraft.",
             "$altim(ICAO)": "The altitude pressure value from the METAR of the station.\nFor availability see $metar",
             "$arr": "The destination airport of the selected aircraft.",
             "$arrrwy[(ICAOs)]": "A comma separated list of the runways set as active for arrivals.\nIf no parameter is defined then the assigned arrival RWY of the ASEL aircraft.",
             "$asquawk": "The assigned SQUAWK code.",
             "$atccallsign [(handoffid)]": "The callsign of the specified controller.\nIf empty then the logged in controller callsign.",
             "$atisairport": "The ICAO code of the airport selected to be served with voice ATIS in the [[Voice ATIS]] dialog.",
             "$atiscode": "The actual ATIS letter specified in the [[Voice ATIS]] dialog.",
             "$bear(position)": "It returns the bearing of the selected aircraft to the specified position.\nPosition can be vor, ndb, fix or airport.",
             "$calt": "The current altitude of the selected aircraft.",
             "$callsign": "The login callsign of the controller.",
             "$com": "The primary frequency of the controller.\nIt will return 199.998 if no primary frequency is selected.",
             "$cruise": "The final cruise altitude of the selected aircraft.",
             "$dep": "The departure airport of the selected aircraft.",
             "$deprwy[(airport ICAO code)]": "A comma separated list of the runways set as active for departures.\nIf no parameter is defined then the assigned departure RWY of the ASEL aircraft.",
             "$dist(position)": "It returns the distance of the selected aircraft to the specified position.\nPosition can be vor, ndb, fix or airport.",
             "$freq[(controller id)]": "If no parameter is given then it returns the primary frequency of the logged in controller (actually the same as $com).\nIf parameter is specified then it returns the primary frequency of the specified controller.",
             "$ftime(minutes)": "The actual GMT time plus the specified minutes.\nFormatted to seconds.",
             "$lc(anything)": "It simply makes the parameter to be lowercase.",
             "$metar(station)": "The complete METAR string of the station.\nWhen you first call this function it may return an empty string.\nIt is because when the METAR is needed EuroScope asks for it from the servers, but the evaluation is not suspended to wait for the result. Therefore and empty string will come, but next time as the METAR arrives it will be displayed correctly.",
             "$myrealname": "The real name of the controller.\nActually the name you specified in the login dialog.",
             "$oclock(position)": "It returns the relative bearing of the selected aircraft to the specified position based on the current heading of the selected aircraft.\nPosition can be vor, ndb, fix or airport.",
             "$radioname[(controller ID)]": "If no parameter is specified then returns the radio name of the active controller.\nOtherwise it looks for the controller based on the short ID.\nThe radio names are defined in the POSITIONS section of the ESE file.",
             "$route": "The route string from the flight plan of the selected aircraft.",
             "$sid": "The assigned or assumed SID of the selected aircraft.",
             "$squawk": "The squawk of the selected aircraft.",
             "$star": "The assigned or assumed STAR of the selected aircraft.",
             "$temp": "The temporary altitude of the selected aircraft.",
             "$time": "The actual GMT time in seconds without the Z sign.",
             "$type [(callsign)]": "The type of the selected aircraft.\nIf the callsign is empty then the type of the ASEL aircraft.",
             "$uc(anything)": "It simply makes the parameter to be uppercase.",
             "$wind [(airport)]": "The wind component of the METAR of the selected station.\nFor availability see $metar.\nIf no airport is defined then looks for the selected aircraft.\nOn the ground it displays the departure airport metar, otherwise the destination airport.", }
